#!/bin/bash
#PBS -l nodes=1:ppn=4,walltime=0:30:00
#PBS -N app-white-matter-mask-fa
#PBS -l vmem=20gb
#PBS -V

set -x
set -e

time singularity exec -e docker://brainlife/fsl:6.0.4-patched2 ./create_wm_mask.sh
